#90 add write permission check

diff --git a/sh/basic/backup b/sh/basic/backup
--- a/sh/basic/backup
+++ b/sh/basic/backup
@@ -6,6 +6,12 @@ if [ $1 == "--help" ]; then
     exit 0
 fi
 
+# Check write permission
+if [ ! -w $(pwd) ]; then
+    echo -e "\033[1;91m[ERROR] Current user doesn't have 'write' permission at this folder. Try using 'sudo' or change to another user. \033[0m"
+    exit 1
+fi
+
 # generating the backup folder
 if [ ! -d "./backup" ]; then
     echo -e "\033[1;91m[WARNING] The folder 'backup' doesn't exist. \033[0m"
diff --git a/sh/fast-build b/sh/fast-build
--- a/sh/fast-build
+++ b/sh/fast-build
@@ -89,6 +89,12 @@ if [ $EUID -ne 0 ]; then
     sleep 2s
 fi
 
+# Check write permission
+if [ ! -w $(pwd) ]; then
+    echo -e "\033[1;91m[ERROR] Current user doesn't have 'write' permission at this folder. Try using 'sudo' or change to another user. \033[0m"
+    exit 1
+fi
+
 # check Java version
 echo -e "\033[1;96m[INFO] Checking Java... \033[0m"
 java -version
diff --git a/sh/replace-variables b/sh/replace-variables
--- a/sh/replace-variables
+++ b/sh/replace-variables
@@ -49,6 +49,13 @@ if [ "$(pwd | grep -E 'sh$')" == "" ]; then
 fi
 
 # ==========================================================
+# Check write permission
+if [ ! -w $(pwd) ]; then
+    echo -e "\033[1;91m[ERROR] Current user doesn't have 'write' permission at this folder. Try using 'sudo' or change to another user. \033[0m"
+    exit 1
+fi
+
+# ==========================================================
 # function for replacing string at specify line in the file
 
 function replace_file() {
